name: AutoUpdateTransAndComits

on : push

jobs:
  updatetransdata:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: SetupPython
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: InstallLibrary
        run: pip install pylightxl
      - name: UpdateTransAndNamePlateData
        run: python update_nameplate_data.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: update-transdata
        with:
          commit_message: AutoCommit Update:trans data
      - name: UpdateTransDataComitHash
        uses: jossef/action-set-json-field@v1
        with:
          file: namePlate/namePlateData.json
          field: updateComitHash
          value: ${{ steps.update-transdata.outputs.commit_hash }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: AutoCommit feat:comit hashs
